# in case gravis-ci disappears I forked it
language: minimal
os:
  - linux
  - windows
env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - JDK="adopt@1.11.0-12"
before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk ; source $GRAVIS/install-maven
cache:
  directories:
    - $HOME/.jabba/
    - $HOME/.m2
script: 
  - mvn --version
  - mvn clean package
